export type PosterStyle = "brush" | "serif" | "sans" | "condensed";

export type Show = {
  slug: string;
  title: string;
  tier: "Broadway" | "Off-Broadway";
  genre: "Musical" | "Play";
  venue: string;
  /** Schema insurance for a future second market (PLAN.md Phase 12); every
   *  current row is NYC — treat absence as "nyc". */
  market?: "nyc";
  /** False for retained catalog entries that are not in the current slate. */
  currentlyRunning?: boolean;
  /** Typical box-office price, used for "below face" anchoring. */
  faceValue: number;
  poster: {
    bg: string;
    fg: string;
    style: PosterStyle;
    /** Poster-art lettering when it differs from the plain title. */
    displayTitle?: string;
    caption?: string;
    captionColor?: string;
    tilt?: number;
  };
};

const SHOWS: Show[] = [
  {
    slug: "the-outsiders",
    title: "The Outsiders",
    tier: "Broadway",
    genre: "Musical",
    venue: 'Bernard B. Jacobs Theatre',
    faceValue: 89,
    poster: {
      bg: "linear-gradient(180deg, #6e6a62 0%, #55524b 45%, #3e3b35 100%)",
      fg: "#d9b13b",
      style: "brush",
      caption: "A New Musical",
      captionColor: "#c9a53d",
    },
  },
  {
    slug: "heathers",
    title: "Heathers",
    tier: "Off-Broadway",
    genre: "Musical",
    venue: 'New World Stages',
    faceValue: 79,
    poster: {
      bg: "linear-gradient(165deg, #22315c 0%, #131b3a 70%, #0c1229 100%)",
      fg: "#e63a2e",
      style: "brush",
      caption: "The Musical",
      captionColor: "#8fd0e8",
    },
  },
  {
    slug: "the-lost-boys",
    title: "The Lost Boys",
    tier: "Broadway",
    genre: "Musical",
    venue: 'Palace Theatre',
    faceValue: 99,
    poster: {
      bg: "radial-gradient(120% 100% at 50% 20%, #4a1104 0%, #230703 55%, #0e0302 100%)",
      fg: "#ff8232",
      style: "serif",
      caption: "A New Musical",
      captionColor: "#b0501f",
    },
  },
  {
    slug: "oh-mary",
    title: "Oh, Mary!",
    tier: "Broadway",
    genre: "Play",
    venue: 'Lyceum Theatre',
    faceValue: 99,
    poster: {
      bg: "#f3c50f",
      fg: "#191512",
      style: "serif",
      displayTitle: "“OH, MARY!”",
      caption: "A New Play by Cole Escola",
      captionColor: "#191512",
    },
  },
  {
    slug: "the-book-of-mormon",
    title: "The Book of Mormon",
    tier: "Broadway",
    genre: "Musical",
    venue: 'Eugene O\'Neill Theatre',
    faceValue: 119,
    poster: {
      bg: "linear-gradient(180deg, #f7f5f0 0%, #e8e4da 100%)",
      fg: "#17130f",
      style: "sans",
      caption: "The Musical",
      captionColor: "#8a8380",
    },
  },
  {
    slug: "operation-mincemeat",
    title: "Operation Mincemeat",
    tier: "Broadway",
    genre: "Musical",
    venue: 'John Golden Theatre',
    faceValue: 94,
    poster: {
      bg: "#f0c419",
      fg: "#17130f",
      style: "condensed",
      caption: "A New Musical",
      captionColor: "#17130f",
    },
  },
  {
    slug: "chess",
    title: "Chess",
    tier: "Broadway",
    genre: "Musical",
    venue: 'Imperial Theatre',
    currentlyRunning: false,
    faceValue: 129,
    poster: {
      bg: "linear-gradient(180deg, #1a1a1f 0%, #0b0b0e 100%)",
      fg: "#e754c4",
      style: "condensed",
      caption: "The Musical",
      captionColor: "#9aa0b5",
    },
  },
  {
    slug: "two-strangers",
    title: "Two Strangers (Carry a Cake Across New York)",
    tier: "Broadway",
    genre: "Musical",
    venue: 'Longacre Theatre',
    faceValue: 89,
    poster: {
      bg: "linear-gradient(180deg, #ffffff 0%, #eef1f7 100%)",
      fg: "#27356e",
      style: "sans",
      caption: "A New Musical Comedy",
      captionColor: "#8a8fa8",
    },
  },
  {
    slug: "maybe-happy-ending",
    title: "Maybe Happy Ending",
    tier: "Broadway",
    genre: "Musical",
    venue: 'Belasco Theatre',
    faceValue: 119,
    poster: {
      bg: "linear-gradient(180deg, #452a78 0%, #241448 60%, #150c2e 100%)",
      fg: "#ffd9a0",
      style: "condensed",
      caption: "Best of the Year",
      captionColor: "#7ee0e8",
    },
  },
  {
    slug: "ragtime",
    title: "Ragtime",
    tier: "Broadway",
    genre: "Musical",
    venue: 'Vivian Beaumont Theater',
    faceValue: 109,
    poster: {
      bg: "#c8102e",
      fg: "#ffffff",
      style: "condensed",
      caption: "The Musical",
      captionColor: "#f3c3cb",
    },
  },
  {
    slug: "death-of-a-salesman",
    title: "Death of a Salesman",
    tier: "Broadway",
    genre: "Play",
    venue: 'Winter Garden Theatre',
    faceValue: 139,
    poster: {
      bg: "#efe9dc",
      fg: "#b3261e",
      style: "serif",
      caption: "By Arthur Miller",
      captionColor: "#5c564e",
    },
  },
  {
    slug: "the-great-gatsby",
    title: "The Great Gatsby",
    tier: "Broadway",
    genre: "Musical",
    venue: "Broadway Theatre",
    faceValue: 99,
    poster: {
      bg: "linear-gradient(160deg, #063f46 0%, #06282e 100%)",
      fg: "#e8c66b",
      style: "serif",
      caption: "A New Musical",
      captionColor: "#c9aa55",
    },
  },
  {
    slug: "aladdin",
    title: "Aladdin",
    tier: "Broadway",
    genre: "Musical",
    venue: "New Amsterdam Theatre",
    faceValue: 89,
    poster: {
      bg: "linear-gradient(180deg, #132d6b 0%, #09173e 100%)",
      fg: "#f4c34e",
      style: "sans",
      caption: "Disney",
      captionColor: "#9fc7ed",
    },
  },
  {
    slug: "just-in-time",
    title: "Just in Time",
    tier: "Broadway",
    genre: "Musical",
    venue: "Circle in the Square Theatre",
    faceValue: 109,
    poster: {
      bg: "linear-gradient(160deg, #701d26 0%, #321016 100%)",
      fg: "#f7e7bd",
      style: "serif",
      caption: "A New Musical",
      captionColor: "#d9ad7d",
    },
  },
  {
    slug: "moulin-rouge",
    title: "Moulin Rouge! The Musical",
    tier: "Broadway",
    genre: "Musical",
    venue: "Al Hirschfeld Theatre",
    faceValue: 99,
    poster: {
      bg: "radial-gradient(circle at 50% 30%, #9d1923 0%, #2c0508 72%)",
      fg: "#f4d0a0",
      style: "serif",
      caption: "The Musical",
      captionColor: "#d8936f",
    },
  },
  {
    slug: "the-lion-king",
    title: "The Lion King",
    tier: "Broadway",
    genre: "Musical",
    venue: "Minskoff Theatre",
    faceValue: 99,
    poster: {
      bg: "linear-gradient(180deg, #e7831c 0%, #9f310c 100%)",
      fg: "#19120d",
      style: "sans",
      caption: "Disney",
      captionColor: "#3d1d10",
    },
  },
  {
    slug: "six",
    title: "SIX: The Musical",
    tier: "Broadway",
    genre: "Musical",
    venue: "Lena Horne Theatre",
    faceValue: 89,
    poster: {
      bg: "linear-gradient(145deg, #7b2e9e 0%, #e23d8f 100%)",
      fg: "#f7e34b",
      style: "condensed",
      caption: "The Musical",
      captionColor: "#f1d5ff",
    },
  },
  {
    slug: "wicked",
    title: "Wicked",
    tier: "Broadway",
    genre: "Musical",
    venue: "Gershwin Theatre",
    faceValue: 109,
    poster: {
      bg: "linear-gradient(145deg, #d8ead3 0%, #8db57e 100%)",
      fg: "#162219",
      style: "serif",
      caption: "The Untold Story of the Witches of Oz",
      captionColor: "#31523a",
    },
  },
  {
    slug: "hadestown",
    title: "Hadestown",
    tier: "Broadway",
    genre: "Musical",
    venue: "Walter Kerr Theatre",
    faceValue: 89,
    poster: {
      bg: "linear-gradient(180deg, #2a1710 0%, #100907 100%)",
      fg: "#d84b2f",
      style: "serif",
      caption: "A Musical",
      captionColor: "#e1ae79",
    },
  },
  {
    slug: "harry-potter-cursed-child",
    title: "Harry Potter and the Cursed Child",
    tier: "Broadway",
    genre: "Play",
    venue: "Lyric Theatre",
    faceValue: 79,
    poster: {
      bg: "linear-gradient(180deg, #17191c 0%, #050607 100%)",
      fg: "#d7b15a",
      style: "serif",
      caption: "The Eighth Story",
      captionColor: "#9d8957",
    },
  },
  {
    slug: "cats-jellicle-ball",
    title: "Cats: The Jellicle Ball",
    tier: "Broadway",
    genre: "Musical",
    venue: "Broadhurst Theatre",
    faceValue: 99,
    poster: {
      bg: "linear-gradient(145deg, #5e278b 0%, #171447 100%)",
      fg: "#ffb037",
      style: "sans",
      caption: "The Jellicle Ball",
      captionColor: "#e988cb",
    },
  },
  {
    slug: "rocky-horror-show",
    title: "The Rocky Horror Show",
    tier: "Broadway",
    genre: "Musical",
    venue: "Studio 54",
    faceValue: 89,
    poster: {
      bg: "linear-gradient(160deg, #8f0717 0%, #190106 100%)",
      fg: "#ffffff",
      style: "brush",
      caption: "Let's Do the Time Warp Again",
      captionColor: "#f0a2ad",
    },
  },
  {
    slug: "stranger-things-first-shadow",
    title: "Stranger Things: The First Shadow",
    tier: "Broadway",
    genre: "Play",
    venue: "Marquis Theatre",
    faceValue: 99,
    poster: {
      bg: "linear-gradient(180deg, #151519 0%, #030304 100%)",
      fg: "#e52b2e",
      style: "condensed",
      caption: "The First Shadow",
      captionColor: "#8d8b90",
    },
  },
  {
    slug: "mj-the-musical",
    title: "MJ The Musical",
    tier: "Broadway",
    genre: "Musical",
    venue: "Neil Simon Theatre",
    faceValue: 99,
    poster: {
      bg: "linear-gradient(180deg, #232323 0%, #070707 100%)",
      fg: "#f2f2f2",
      style: "sans",
      caption: "The Music. The Moves. The Michael.",
      captionColor: "#a6a6a6",
    },
  },
  {
    slug: "and-juliet",
    title: "& Juliet",
    tier: "Broadway",
    genre: "Musical",
    venue: "Stephen Sondheim Theatre",
    faceValue: 89,
    poster: {
      bg: "linear-gradient(145deg, #ff7fae 0%, #7d49bd 100%)",
      fg: "#fff5d6",
      style: "sans",
      caption: "Created by David West Read",
      captionColor: "#dff4ff",
    },
  },
  {
    slug: "schmigadoon",
    title: "Schmigadoon!",
    tier: "Broadway",
    genre: "Musical",
    venue: "Nederlander Theatre",
    faceValue: 99,
    poster: {
      bg: "linear-gradient(160deg, #f0d863 0%, #8ac6d0 100%)",
      fg: "#523349",
      style: "serif",
      caption: "A New Musical",
      captionColor: "#4d6774",
    },
  },
  {
    slug: "every-brilliant-thing",
    title: "Every Brilliant Thing",
    tier: "Broadway",
    genre: "Play",
    venue: "Hudson Theatre",
    faceValue: 89,
    poster: {
      bg: "#f3db35",
      fg: "#1c1810",
      style: "sans",
      caption: "A Play",
      captionColor: "#6e5f19",
    },
  },
  {
    slug: "hamilton",
    title: "Hamilton",
    tier: "Broadway",
    genre: "Musical",
    venue: "Richard Rodgers Theatre",
    faceValue: 139,
    poster: {
      bg: "linear-gradient(180deg, #e9d9aa 0%, #b99b5b 100%)",
      fg: "#17120c",
      style: "serif",
      caption: "An American Musical",
      captionColor: "#59472d",
    },
  },
  {
    slug: "joe-turners-come-and-gone",
    title: "Joe Turner's Come and Gone",
    tier: "Broadway",
    genre: "Play",
    venue: "Ethel Barrymore Theatre",
    faceValue: 89,
    poster: {
      bg: "linear-gradient(160deg, #6d3f25 0%, #28180f 100%)",
      fg: "#f0d4a3",
      style: "serif",
      caption: "By August Wilson",
      captionColor: "#b99363",
    },
  },
  {
    slug: "chicago",
    title: "Chicago",
    tier: "Broadway",
    genre: "Musical",
    venue: "Ambassador Theatre",
    faceValue: 79,
    poster: {
      bg: "linear-gradient(180deg, #161616 0%, #030303 100%)",
      fg: "#e52c28",
      style: "condensed",
      caption: "The Musical",
      captionColor: "#e8e3db",
    },
  },
  {
    slug: "titanique",
    title: "Titaníque",
    tier: "Broadway",
    genre: "Musical",
    venue: "St. James Theatre",
    faceValue: 79,
    poster: {
      bg: "linear-gradient(180deg, #78b8d5 0%, #173d65 100%)",
      fg: "#f7f5eb",
      style: "serif",
      caption: "The Musical",
      captionColor: "#d1e7f0",
    },
  },
  {
    slug: "proof",
    title: "Proof",
    tier: "Broadway",
    genre: "Play",
    venue: "Booth Theatre",
    faceValue: 89,
    poster: {
      bg: "linear-gradient(180deg, #f1efe8 0%, #d3cec1 100%)",
      fg: "#1d1b19",
      style: "sans",
      caption: "By David Auburn",
      captionColor: "#68625a",
    },
  },
  {
    slug: "buena-vista-social-club",
    title: "Buena Vista Social Club",
    tier: "Broadway",
    genre: "Musical",
    venue: "Gerald Schoenfeld Theatre",
    faceValue: 99,
    poster: {
      bg: "linear-gradient(145deg, #bd6d27 0%, #3d5d3b 100%)",
      fg: "#f5dfad",
      style: "serif",
      caption: "A New Musical",
      captionColor: "#e6c277",
    },
  },

  /*
   * Off-Broadway slate (Phase 12), verified against the July 2026 listings
   * (Playbill / NYTG / show sites, checked 2026-07-16). Long-runners first,
   * then this month's openings. Posters render as typographic tiles.
   */
  {
    slug: "little-shop-of-horrors",
    title: "Little Shop of Horrors",
    tier: "Off-Broadway",
    genre: "Musical",
    venue: "Westside Theatre",
    faceValue: 89,
    poster: {
      bg: "linear-gradient(180deg, #14401f 0%, #0a2412 100%)",
      fg: "#8fe06a",
      style: "brush",
      caption: "The Musical",
      captionColor: "#d84a3b",
    },
  },
  {
    slug: "the-play-that-goes-wrong",
    title: "The Play That Goes Wrong",
    tier: "Off-Broadway",
    genre: "Play",
    venue: "New World Stages",
    faceValue: 79,
    poster: {
      bg: "linear-gradient(172deg, #7a1f1f 0%, #4a1010 100%)",
      fg: "#f3e3c2",
      style: "condensed",
      tilt: 5,
      caption: "A Comedy (Mostly)",
      captionColor: "#d8a94e",
    },
  },
  {
    slug: "perfect-crime",
    title: "Perfect Crime",
    tier: "Off-Broadway",
    genre: "Play",
    venue: "The Theater Center",
    faceValue: 79,
    poster: {
      bg: "linear-gradient(180deg, #1c1c22 0%, #0d0d12 100%)",
      fg: "#d43a3a",
      style: "serif",
      caption: "Year 40 · NYC's Longest-Running Play",
      captionColor: "#8f8f9a",
    },
  },
  {
    slug: "spelling-bee",
    title: "The 25th Annual Putnam County Spelling Bee",
    tier: "Off-Broadway",
    genre: "Musical",
    venue: "New World Stages — Stage 3",
    faceValue: 79,
    poster: {
      bg: "#f2d43c",
      fg: "#233a8f",
      style: "sans",
      displayTitle: "SPELLING BEE",
      caption: "The Tony-Winning Musical",
      captionColor: "#233a8f",
    },
  },
  {
    slug: "gazillion-bubble-show",
    title: "Gazillion Bubble Show",
    tier: "Off-Broadway",
    genre: "Play",
    venue: "New World Stages — Stage 2",
    faceValue: 69,
    poster: {
      bg: "linear-gradient(200deg, #2a6db8 0%, #133a6e 100%)",
      fg: "#bfe6ff",
      style: "brush",
      caption: "Final Months — 19 Years of Bubbles",
      captionColor: "#7fc4f0",
    },
  },
  {
    slug: "the-gin-game",
    title: "The Gin Game",
    tier: "Off-Broadway",
    genre: "Play",
    venue: "Housing Works Bookstore",
    faceValue: 89,
    poster: {
      bg: "linear-gradient(180deg, #efe4cf 0%, #ddcba6 100%)",
      fg: "#7a2c1d",
      style: "serif",
      caption: "Among the Bookshelves · Closes Aug 9",
      captionColor: "#8a6f4d",
    },
  },
  {
    slug: "drunk-shakespeare",
    title: "Drunk Shakespeare",
    tier: "Off-Broadway",
    genre: "Play",
    venue: "The Ruby Theatre",
    faceValue: 69,
    poster: {
      bg: "linear-gradient(160deg, #4a1233 0%, #24081a 100%)",
      fg: "#e8b64c",
      style: "serif",
      caption: "Five Actors. One Whiskey.",
      captionColor: "#b98cae",
    },
  },
  {
    slug: "accomplice-the-show",
    title: "Accomplice: The Show",
    tier: "Off-Broadway",
    genre: "Play",
    venue: "Greenwich Village (immersive)",
    faceValue: 79,
    poster: {
      bg: "linear-gradient(180deg, #33402a 0%, #1b2416 100%)",
      fg: "#e3d9b8",
      style: "condensed",
      tilt: -3,
      caption: "Solve It on the Streets",
      captionColor: "#9fae86",
    },
  },
  {
    slug: "shifters",
    title: "Shifters",
    tier: "Off-Broadway",
    genre: "Play",
    venue: "Cherry Lane Theatre",
    faceValue: 69,
    poster: {
      bg: "linear-gradient(180deg, #2c2440 0%, #191430 100%)",
      fg: "#f0a8c0",
      style: "sans",
      caption: "By Benedict Lombe",
      captionColor: "#9d92c4",
    },
  },
  {
    slug: "the-whoopi-monologues",
    title: "The Whoopi Monologues",
    tier: "Off-Broadway",
    genre: "Play",
    venue: "Mitzi E. Newhouse Theater",
    faceValue: 99,
    poster: {
      bg: "linear-gradient(180deg, #46215c 0%, #2a1138 100%)",
      fg: "#f2c94c",
      style: "brush",
      caption: "By Whoopi Goldberg",
      captionColor: "#c9a3de",
    },
  },
  {
    slug: "broad-strokes",
    title: "Broad Strokes",
    tier: "Off-Broadway",
    genre: "Musical",
    venue: "Lucille Lortel Theatre",
    faceValue: 89,
    poster: {
      bg: "#e9dcc8",
      fg: "#c2452e",
      style: "brush",
      tilt: -6,
      caption: "A New Musical by Cat Cohen",
      captionColor: "#7a6a52",
    },
  },
  {
    slug: "the-saviors",
    title: "The Saviors",
    tier: "Off-Broadway",
    genre: "Play",
    venue: "Linda Gross Theater",
    faceValue: 69,
    poster: {
      bg: "linear-gradient(180deg, #5b6770 0%, #333d44 100%)",
      fg: "#f4efe6",
      style: "serif",
      caption: "Atlantic Theater Company",
      captionColor: "#aab4ba",
    },
  },
  {
    slug: "giulia-poison-queen",
    title: "Giulia: The Poison Queen of Palermo",
    tier: "Off-Broadway",
    genre: "Musical",
    venue: "Perelman Performing Arts Center",
    faceValue: 99,
    poster: {
      bg: "linear-gradient(170deg, #64152e 0%, #37081a 100%)",
      fg: "#e8c874",
      style: "serif",
      displayTitle: "GIULIA",
      caption: "Music & Lyrics by Jennifer Nettles",
      captionColor: "#c98da2",
    },
  },
  {
    slug: "disruption",
    title: "Disruption",
    tier: "Off-Broadway",
    genre: "Play",
    venue: "Pershing Square Signature Center",
    faceValue: 59,
    poster: {
      bg: "#101418",
      fg: "#5fe0c8",
      style: "condensed",
      caption: "Previews Begin July 22",
      captionColor: "#5b6a72",
    },
  },
];

export function allShows(): Show[] {
  return SHOWS;
}

export function currentBroadwayShows(): Show[] {
  return SHOWS.filter(
    (show) => show.tier === "Broadway" && show.currentlyRunning !== false,
  );
}

export function getShow(slug: string): Show | undefined {
  return SHOWS.find((s) => s.slug === slug);
}

/** Non-null lookup for internal mock data that references known slugs. */
export function show(slug: string): Show {
  const found = getShow(slug);
  if (!found) throw new Error(`Unknown show slug: ${slug}`);
  return found;
}
